
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mias?nullDatabaseMeansCurrent=true
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 50MB
  jackson:
    time-zone: Asia/Shanghai

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Camunda related configurations
camunda:
  bpm:
    database:
      type: mysql
      schema-update: true
    auto-deployment-enabled: true
    # Camunda admin user credentials
    admin-user:
      id: admin
      password: 12345
    webapp:
      application-path: process
logging:
  level:
    #配置日志，这样在开发过程中就能看到每步执行的SQL语句了
    '[org.camunda.bpm.engine.impl.persistence.entity]': DEBUG

server:
  port: 8080